package importer

import (
	"bytes"
	"strings"
	"testing"
)

func TestRun_HeaderAndSettings(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	for _, want := range []string{
		"Generated by `bigkis import`",
		"[settings]",
		`enabled      = ["pacman", "aur", "flatpak", "node"]`,
		`aur_helper   = "yay"`,
		`node_manager = "npm"`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in output:\n%s", want, out)
		}
	}
}

func TestRun_OnlyFiltersSections(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{Only: []string{"flatpak"}}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "[pacman]") {
		t.Errorf("pacman section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if strings.Contains(out, "[aur]") {
		t.Errorf("aur section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if strings.Contains(out, "[node]") {
		t.Errorf("node section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if !strings.Contains(out, "[flatpak]") {
		t.Errorf("flatpak section missing in:\n%s", out)
	}
}

func TestRun_CustomScalars(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{AURHelper: "paru", NodeManager: "pnpm"}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `aur_helper   = "paru"`) {
		t.Errorf("custom aur_helper missing:\n%s", out)
	}
	if !strings.Contains(out, `node_manager = "pnpm"`) {
		t.Errorf("custom node_manager missing:\n%s", out)
	}
}

func TestWriteStringList_EmptyEmitsBrackets(t *testing.T) {
	var buf bytes.Buffer
	writeStringList(&buf, "packages", nil)
	if got := strings.TrimSpace(buf.String()); got != "packages = []" {
		t.Errorf("empty list = %q, want 'packages = []'", got)
	}
}

func TestWriteStringList_DedupsAndSorts(t *testing.T) {
	var buf bytes.Buffer
	writeStringList(&buf, "packages", []string{"git", "base", "git", "base"})
	got := buf.String()
	if !strings.Contains(got, `"base"`) || !strings.Contains(got, `"git"`) {
		t.Errorf("missing entries: %s", got)
	}
	if strings.Count(got, `"git"`) != 1 {
		t.Errorf("git not deduped: %s", got)
	}
	// Sort: base before git.
	if strings.Index(got, `"base"`) > strings.Index(got, `"git"`) {
		t.Errorf("not sorted: %s", got)
	}
}

func TestStripFlatpakHeader(t *testing.T) {
	in := []string{"Application", "org.mozilla.firefox", "org.signal.Signal"}
	got := stripFlatpakHeader(in)
	if len(got) != 2 || got[0] != "org.mozilla.firefox" {
		t.Errorf("strip = %v, want without header", got)
	}
}
