package importer

import (
	"bytes"
	"strings"
	"testing"
)

func TestRun_HeaderAndSettings(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	for _, want := range []string{
		"Generated by `bigkis import`",
		"[settings]",
		`enabled      = ["pacman", "aur", "flatpak", "node"]`,
		`aur_helper   = "yay"`,
		`node_manager = "npm"`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in output:\n%s", want, out)
		}
	}
}

func TestRun_OnlyFiltersSections(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{Only: []string{"flatpak"}}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "[pacman]") {
		t.Errorf("pacman section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if strings.Contains(out, "[aur]") {
		t.Errorf("aur section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if strings.Contains(out, "[node]") {
		t.Errorf("node section should be omitted when Only=[flatpak]:\n%s", out)
	}
	if !strings.Contains(out, "[flatpak]") {
		t.Errorf("flatpak section missing in:\n%s", out)
	}
}

// TestRun_OnlyTrimsEnabledList guards the regression where importing only
// flatpak still wrote settings.enabled = ["pacman", "aur", "flatpak", "node"]
// and so the next bigkis apply queued removals for sections we never wrote.
func TestRun_OnlyTrimsEnabledList(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{Only: []string{"flatpak"}}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `enabled      = ["flatpak"]`) {
		t.Errorf("expected enabled list trimmed to flatpak only, got:\n%s", out)
	}
}

func TestEnabledList_IgnoresUnknownAndDedupes(t *testing.T) {
	got := enabledList([]string{"flatpak", "flatpak", "snap", "pacman"})
	want := `["flatpak", "pacman"]`
	if got != want {
		t.Errorf("enabledList = %q, want %q", got, want)
	}
}

func TestEnabledList_EmptyOnlyKeepsAll(t *testing.T) {
	got := enabledList(nil)
	want := `["pacman", "aur", "flatpak", "node"]`
	if got != want {
		t.Errorf("enabledList(nil) = %q, want %q", got, want)
	}
}

func TestRun_CustomScalars(t *testing.T) {
	var buf bytes.Buffer
	if err := Run(&buf, Options{AURHelper: "paru", NodeManager: "pnpm"}); err != nil {
		t.Fatalf("Run: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `aur_helper   = "paru"`) {
		t.Errorf("custom aur_helper missing:\n%s", out)
	}
	if !strings.Contains(out, `node_manager = "pnpm"`) {
		t.Errorf("custom node_manager missing:\n%s", out)
	}
}

func TestWriteStringList_EmptyEmitsBrackets(t *testing.T) {
	var buf bytes.Buffer
	writeStringList(&buf, "packages", nil)
	if got := strings.TrimSpace(buf.String()); got != "packages = []" {
		t.Errorf("empty list = %q, want 'packages = []'", got)
	}
}

func TestWriteStringList_DedupsAndSorts(t *testing.T) {
	var buf bytes.Buffer
	writeStringList(&buf, "packages", []string{"git", "base", "git", "base"})
	got := buf.String()
	if !strings.Contains(got, `"base"`) || !strings.Contains(got, `"git"`) {
		t.Errorf("missing entries: %s", got)
	}
	if strings.Count(got, `"git"`) != 1 {
		t.Errorf("git not deduped: %s", got)
	}
	// Sort: base before git.
	if strings.Index(got, `"base"`) > strings.Index(got, `"git"`) {
		t.Errorf("not sorted: %s", got)
	}
}

func TestStripFlatpakHeader(t *testing.T) {
	in := []string{"Application", "org.mozilla.firefox", "org.signal.Signal"}
	got := stripFlatpakHeader(in)
	if len(got) != 2 || got[0] != "org.mozilla.firefox" {
		t.Errorf("strip = %v, want without header", got)
	}
}

func TestRunSelected_WithSelection(t *testing.T) {
	var buf bytes.Buffer
	sel := Selection{
		Pacman:  []string{"base", "linux", "vim"},
		AUR:     []string{"aurpkg-a", "aurpkg-b"},
		Flatpak: []string{"org.mozilla.firefox"},
		Node:    []NodePackage{{Name: "typescript", Manager: "npm"}},
	}
	if err := RunSelected(&buf, Options{}, sel); err != nil {
		t.Fatalf("RunSelected: %v", err)
	}
	out := buf.String()

	// Header and settings
	for _, want := range []string{
		"Generated by `bigkis import`",
		"[settings]",
		`enabled      = ["pacman", "aur", "flatpak", "node"]`,
		`aur_helper   = "yay"`,
		`node_manager = "npm"`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in output:\n%s", want, out)
		}
	}

	// Pacman packages appear
	for _, pkg := range sel.Pacman {
		if !strings.Contains(out, `"`+pkg+`"`) {
			t.Errorf("expected pacman package %q in output:\n%s", pkg, out)
		}
	}

	// AUR packages appear
	for _, pkg := range sel.AUR {
		if !strings.Contains(out, `"`+pkg+`"`) {
			t.Errorf("expected AUR package %q in output:\n%s", pkg, out)
		}
	}

	// Flatpak packages appear
	for _, pkg := range sel.Flatpak {
		if !strings.Contains(out, `"`+pkg+`"`) {
			t.Errorf("expected flatpak package %q in output:\n%s", pkg, out)
		}
	}

	// Node package appears
	for _, pkg := range sel.Node {
		if !strings.Contains(out, `"`+pkg.Name+`"`) {
			t.Errorf("expected node package %q in output:\n%s", pkg.Name, out)
		}
	}

	// Section headers present
	for _, sec := range []string{"[pacman]", "[aur]", "[flatpak]", "[node]"} {
		if !strings.Contains(out, sec) {
			t.Errorf("missing section %s in output:\n%s", sec, out)
		}
	}
}

func TestRunSelected_EmptySelection(t *testing.T) {
	var buf bytes.Buffer
	sel := Selection{}
	if err := RunSelected(&buf, Options{}, sel); err != nil {
		t.Fatalf("RunSelected: %v", err)
	}
	out := buf.String()

	// All section headers should still appear
	for _, sec := range []string{"[pacman]", "[aur]", "[flatpak]", "[node]"} {
		if !strings.Contains(out, sec) {
			t.Errorf("missing section %s in output:\n%s", sec, out)
		}
	}

	// All package lists should be empty (= [])
	if !strings.Contains(out, "packages = []") {
		t.Errorf("expected empty packages in all sections:\n%s", out)
	}
	if !strings.Contains(out, "ignored  = []") {
		t.Errorf("expected ignored = [] in all sections:\n%s", out)
	}
}

func TestRunSelected_OnlyFilter(t *testing.T) {
	var buf bytes.Buffer
	sel := Selection{
		Pacman:  []string{"base", "linux"},
		Flatpak: []string{"org.mozilla.firefox"},
	}
	if err := RunSelected(&buf, Options{Only: []string{"pacman"}}, sel); err != nil {
		t.Fatalf("RunSelected: %v", err)
	}
	out := buf.String()

	if !strings.Contains(out, "[pacman]") {
		t.Errorf("pacman section should be present:\n%s", out)
	}
	if strings.Contains(out, "[aur]") {
		t.Errorf("aur section should be omitted when Only=[pacman]:\n%s", out)
	}
	if strings.Contains(out, "[flatpak]") {
		t.Errorf("flatpak section should be omitted when Only=[pacman]:\n%s", out)
	}
	if strings.Contains(out, "[node]") {
		t.Errorf("node section should be omitted when Only=[pacman]:\n%s", out)
	}
	if !strings.Contains(out, `enabled      = ["pacman"]`) {
		t.Errorf("expected enabled list trimmed to pacman only, got:\n%s", out)
	}
}

func TestRun_And_RunSelected_ProduceIdenticalOutput(t *testing.T) {
	if !hasCommand("pacman") {
		t.Skip("skipping: requires pacman (Arch Linux)")
	}

	var buf1, buf2 bytes.Buffer

	// Collect scanned packages from the live system
	pacmanPkgs, pacmanErr := ScanPacman()
	aurPkgs, aurErr := ScanAUR()
	flatpakPkgs, flatpakErr := ScanFlatpak()
	nodePkgs, nodeErr := ScanNode()

	opts := Options{}
	sel := Selection{
		Pacman:  pacmanPkgs,
		AUR:     aurPkgs,
		Flatpak: flatpakPkgs,
		Node:    nodePkgs,
	}

	Run(&buf1, opts)
	RunSelected(&buf2, opts, sel)

	// If any scanner had an error, Run will include error comments in the
	// output while RunSelected passes nil errors. Skip in that case so we
	// only compare when both paths produce identical output.
	if pacmanErr != nil || aurErr != nil || flatpakErr != nil || nodeErr != nil {
		t.Skip("skipping: scan errors detected; Run vs RunSelected output would differ due to error comments")
	}

	if buf1.String() != buf2.String() {
		t.Errorf("Run and RunSelected produced different output\n--- Run:\n%s\n--- RunSelected:\n%s", buf1.String(), buf2.String())
	}
}

func TestRunSelected_NodeDefaultsAndOverrides(t *testing.T) {
	var buf bytes.Buffer
	sel := Selection{
		Node: []NodePackage{
			{Name: "lodash", Manager: "npm"},
			{Name: "webpack", Manager: "pnpm"},
			{Name: "jest", Manager: "yarn"},
		},
	}
	// default node manager = npm, so lodash goes to packages, webpack and jest get [[node.package]]
	if err := RunSelected(&buf, Options{NodeManager: "npm"}, sel); err != nil {
		t.Fatalf("RunSelected: %v", err)
	}
	out := buf.String()

	if !strings.Contains(out, `"lodash"`) {
		t.Errorf("expected lodash in packages:\n%s", out)
	}
	if !strings.Contains(out, `"webpack"`) {
		t.Errorf("expected webpack in output:\n%s", out)
	}
	if !strings.Contains(out, `"jest"`) {
		t.Errorf("expected jest in output:\n%s", out)
	}
	// lodash is default (npm) manager — should be in packages list, not [[node.package]]
	if strings.Contains(out, `[[node.package]]`) {
		// The [[node.package]] blocks should only appear for non-default managers
		// Count the occurrences
		count := strings.Count(out, "[[node.package]]")
		if count != 2 {
			t.Errorf("expected 2 [[node.package]] blocks, got %d:\n%s", count, out)
		}
	}
}
