// Package importer scans the current system and emits a starter system.toml.
//
// It is intentionally independent of the plugin packages: it shells out to
// pacman/flatpak/npm/pnpm/yarn directly so it can run on a system that does
// not yet have a bigkis config or state file.
package importer

import (
	"encoding/json"
	"fmt"
	"io"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"
)

// Options controls what gets imported.
type Options struct {
	// Only restricts the import to a subset of plugin names. Empty means "all".
	Only []string
	// AURHelper sets the [settings].aur_helper value in the output.
	AURHelper string
	// NodeManager sets the [settings].node_manager value in the output.
	NodeManager string
}

// Run writes a TOML config representing the current system to out.
func Run(out io.Writer, opts Options) error {
	want := buildSelector(opts.Only)

	aurHelper := opts.AURHelper
	if aurHelper == "" {
		aurHelper = "yay"
	}
	nodeManager := opts.NodeManager
	if nodeManager == "" {
		nodeManager = "npm"
	}

	fmt.Fprintf(out, header, time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(out, "[settings]")
	fmt.Fprintln(out, `enabled      = ["pacman", "aur", "flatpak", "node"]`)
	fmt.Fprintf(out, "aur_helper   = %q\n", aurHelper)
	fmt.Fprintf(out, "node_manager = %q\n", nodeManager)
	fmt.Fprintln(out)

	if want("pacman") {
		writePacmanSection(out)
	}
	if want("aur") {
		writeAURSection(out)
	}
	if want("flatpak") {
		writeFlatpakSection(out)
	}
	if want("node") {
		writeNodeSection(out, nodeManager)
	}
	return nil
}

const header = `# Generated by ` + "`bigkis import`" + ` on %s.
#
# IMPORTANT: review and curate this file before applying. The importer simply
# dumps what is currently installed on this machine; you almost certainly
# want to remove transient or experimental packages, organize related
# packages into [groups], and add per-user flatpak entries that the importer
# cannot infer.
#
# After curating:
#   bigkis check  -c system.toml
#   bigkis status -c system.toml
#   sudo bigkis apply --dry-run -c system.toml
#   sudo bigkis apply -c system.toml

`

func writePacmanSection(out io.Writer) {
	pkgs, err := captureLines("pacman", "-Qqen")
	fmt.Fprintln(out, "[pacman]")
	if err != nil {
		fmt.Fprintf(out, "# pacman probe failed: %s\n", err)
		fmt.Fprintln(out, "packages = []")
		fmt.Fprintln(out, "ignored  = []")
		fmt.Fprintln(out)
		return
	}
	writeStringList(out, "packages", pkgs)
	fmt.Fprintln(out, "ignored  = []")
	fmt.Fprintln(out)
}

func writeAURSection(out io.Writer) {
	pkgs, err := captureLines("pacman", "-Qqm")
	fmt.Fprintln(out, "[aur]")
	if err != nil {
		// pacman -Qqm exits 1 when no foreign packages exist; treat as empty.
		if isExitOne(err) {
			pkgs = nil
		} else {
			fmt.Fprintf(out, "# aur probe failed: %s\n", err)
			fmt.Fprintln(out, "packages = []")
			fmt.Fprintln(out, "ignored  = []")
			fmt.Fprintln(out)
			return
		}
	}
	writeStringList(out, "packages", pkgs)
	fmt.Fprintln(out, "ignored  = []")
	fmt.Fprintln(out)
}

func writeFlatpakSection(out io.Writer) {
	fmt.Fprintln(out, "[flatpak]")
	if !hasCommand("flatpak") {
		fmt.Fprintln(out, "# flatpak not installed; skipping system probe")
		fmt.Fprintln(out, "packages = []")
		fmt.Fprintln(out, "ignored  = []")
		fmt.Fprintln(out, "[flatpak.user_packages]")
		fmt.Fprintln(out, "# Add per-user flatpaks here, e.g. alice = [\"com.valvesoftware.Steam\"]")
		fmt.Fprintln(out)
		return
	}

	pkgs, err := captureLines("flatpak", "list", "--app", "--system", "--columns=application")
	if err != nil {
		fmt.Fprintf(out, "# flatpak probe failed: %s\n", err)
		pkgs = nil
	}
	pkgs = stripFlatpakHeader(pkgs)
	writeStringList(out, "packages", pkgs)
	fmt.Fprintln(out, "ignored  = []")
	fmt.Fprintln(out, "[flatpak.user_packages]")
	fmt.Fprintln(out, "# Per-user flatpaks are NOT auto-imported. Add them manually:")
	fmt.Fprintln(out, "# alice = [\"com.valvesoftware.Steam\"]")
	fmt.Fprintln(out)
}

func writeNodeSection(out io.Writer, defaultMgr string) {
	fmt.Fprintln(out, "[node]")

	type pkgEntry struct {
		Name    string
		Manager string
	}

	managers := []string{"npm", "pnpm", "yarn"}
	var entries []pkgEntry
	for _, mgr := range managers {
		if !hasCommand(mgr) {
			continue
		}
		pkgs, err := probeNodeManager(mgr)
		if err != nil {
			fmt.Fprintf(out, "# %s probe failed: %s\n", mgr, err)
			continue
		}
		for _, p := range pkgs {
			entries = append(entries, pkgEntry{Name: p, Manager: mgr})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Manager != entries[j].Manager {
			return entries[i].Manager < entries[j].Manager
		}
		return entries[i].Name < entries[j].Name
	})

	// Anything installed via the default manager goes into [node].packages
	// without a per-package override.
	var defaults []string
	var overrides []pkgEntry
	for _, e := range entries {
		if e.Manager == defaultMgr {
			defaults = append(defaults, e.Name)
		} else {
			overrides = append(overrides, e)
		}
	}
	writeStringList(out, "packages", defaults)
	for _, o := range overrides {
		fmt.Fprintln(out, "[[node.package]]")
		fmt.Fprintf(out, "name    = %q\n", o.Name)
		fmt.Fprintf(out, "manager = %q\n", o.Manager)
	}
}

// helpers

func buildSelector(only []string) func(string) bool {
	if len(only) == 0 {
		return func(string) bool { return true }
	}
	set := map[string]struct{}{}
	for _, n := range only {
		set[n] = struct{}{}
	}
	return func(name string) bool {
		_, ok := set[name]
		return ok
	}
}

func captureLines(name string, args ...string) ([]string, error) {
	out, err := exec.Command(name, args...).Output()
	if err != nil {
		return nil, err
	}
	return splitLines(string(out)), nil
}

func splitLines(s string) []string {
	var out []string
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// `pacman -Qm` prints "name version"; take only the package name.
		fields := strings.Fields(line)
		out = append(out, fields[0])
	}
	return out
}

func stripFlatpakHeader(in []string) []string {
	var out []string
	for _, line := range in {
		if strings.HasPrefix(line, "Application") {
			continue
		}
		out = append(out, line)
	}
	return out
}

func hasCommand(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func isExitOne(err error) bool {
	if err == nil {
		return false
	}
	if ee, ok := err.(*exec.ExitError); ok {
		return ee.ExitCode() == 1
	}
	return false
}

func writeStringList(out io.Writer, key string, items []string) {
	uniq := dedup(items)
	sort.Strings(uniq)
	if len(uniq) == 0 {
		fmt.Fprintf(out, "%s = []\n", key)
		return
	}
	fmt.Fprintf(out, "%s = [\n", key)
	for _, x := range uniq {
		fmt.Fprintf(out, "  %q,\n", x)
	}
	fmt.Fprintln(out, "]")
}

func dedup(items []string) []string {
	seen := map[string]struct{}{}
	var out []string
	for _, x := range items {
		if x == "" {
			continue
		}
		if _, ok := seen[x]; ok {
			continue
		}
		seen[x] = struct{}{}
		out = append(out, x)
	}
	return out
}

// node probes mirror what the node plugin does, kept in sync intentionally.

func probeNodeManager(mgr string) ([]string, error) {
	switch mgr {
	case "npm", "pnpm":
		return probeNPMLike(mgr)
	case "yarn":
		return probeYarn()
	}
	return nil, fmt.Errorf("unknown node manager %q", mgr)
}

func probeNPMLike(mgr string) ([]string, error) {
	out, _ := exec.Command(mgr, "ls", "-g", "--depth=0", "--json").Output()
	if len(out) == 0 {
		return nil, nil
	}
	type listOutput struct {
		Dependencies map[string]any `json:"dependencies"`
	}
	var arr []listOutput
	if err := json.Unmarshal(out, &arr); err == nil && len(arr) > 0 {
		var names []string
		for _, l := range arr {
			for k := range l.Dependencies {
				names = append(names, k)
			}
		}
		return names, nil
	}
	var single listOutput
	if err := json.Unmarshal(out, &single); err == nil {
		var names []string
		for k := range single.Dependencies {
			names = append(names, k)
		}
		return names, nil
	}
	return nil, fmt.Errorf("could not parse %s output", mgr)
}

var yarnInfoLine = regexp.MustCompile(`^info "(.+)@[^"]+" has binaries`)

func probeYarn() ([]string, error) {
	out, err := exec.Command("yarn", "global", "list", "--depth=0").Output()
	if err != nil {
		return nil, err
	}
	var names []string
	for _, line := range strings.Split(string(out), "\n") {
		m := yarnInfoLine.FindStringSubmatch(strings.TrimSpace(line))
		if len(m) == 2 {
			names = append(names, m[1])
		}
	}
	return names, nil
}
